### PR TITLE
Use and fix of CLUEHits

### LINKED ISSUE #12: Enhancement and use of CaloHits output collection
Currently I create two collections in output:
- `CLUEClusters` which is `edm4hep::ClusterCollection`
- `Output_hits` which is `edm4hep::CalorimeterHitCollection`
The second collection is just a _translation_ of the Clusters in CaloHits so that we can try to give them in input in the `PandoraPFA` algo and study possible improvements.

To do list:
- [x] rename `Output_hits` in `CLUEHits`
- [x] modify `gaudi_opts/clicRec_e4h_input_clue.py` to make Pandora use of them
- [x] document the code in a clearer way (i.e. `fake` name is misleading)
- [ ] check parameters of both `CLUEHits` and `CLUEClusters`

### PR DESCRIPTION
**Pull request by ebrondol**
BEGINRELEASENOTES
- Rename `Output_hits` in `CLUEHits`
- Modify `gaudi_opts/clicRec_e4h_input_clue.py` to make Pandora use of them
- Document the code in a clearer way (i.e. `fake` name is misleading)

ENDRELEASENOTES

- @vvolkl could you please check in `include/IO_helper.h` if the parameters of both `CLUEHits` and `CLUEClusters` output collections are correctly calculated and set? A second eye would help, thanks.
- Fix #12 
- Thanks @fdplacido for the help

### CODE REVIEW

**Comment by ebrondol** [comment]
first ping of @vvolkl  in 2022 :wink:

**Comment by vvolkl** [comment]
Hi @ebrondol, sorry for the delay, and happy 2022 ;) The changes in this PR look good to me. With regards to `include/IO_helpers.py`,  I have a few comments, but I think I'll need to go over the whole code again, the usage currently isn't clear to me.

https://github.com/key4hep/k4Clue/blob/main/include/IO_helper.h#L18 : This should now be possible to take from the collection metadata instead of hardcoding it, no?

https://github.com/key4hep/k4Clue/blob/main/include/IO_helper.h#L34 : The naming of the variables x, y is a bit confusing as they are filled with eta and phi, right? If there's a good reason to use x, y, it will be good to comment on it.

**Comment by ebrondol** [comment]
Hello @vvolkl ! Thanks for looking at it.

> https://github.com/key4hep/k4Clue/blob/main/include/IO_helper.h#L18 : This should now be possible to take from the collection metadata instead of hardcoding it, no?

could you give me an example? I'd be very happy to remove this hardcoded line from the code.

> https://github.com/key4hep/k4Clue/blob/main/include/IO_helper.h#L34 : The naming of the variables x, y is a bit confusing as they are filled with eta and phi, right? If there's a good reason to use x, y, it will be good to comment on it.

Done. I would keep `x` and `y` in the rest of the code because this is the nomenclature used in the algo itself.

**Comment by ebrondol** [comment]
> > https://github.com/key4hep/k4Clue/blob/main/include/IO_helper.h#L18 : This should now be possible to take from the collection metadata instead of hardcoding it, no?
> 
> could you give me an example? I'd be very happy to remove this hardcoded line from the code.

Please have a look at the latest commit where I address this comment.

**Pull request merged**
